// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDrYJxXUojWLZ_wCoTq8IXlF6KJwcYyM4',
    appId: '1:876858730068:web:5bedb6574e4198691cefc1',
    messagingSenderId: '876858730068',
    projectId: 'pushnotifcationdemo-bf646',
    authDomain: 'pushnotifcationdemo-bf646.firebaseapp.com',
    storageBucket: 'pushnotifcationdemo-bf646.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB19KYzNB7nXtuDQef79R5Te0zoIvjFeQk',
    appId: '1:876858730068:android:dd62411108f3c7f51cefc1',
    messagingSenderId: '876858730068',
    projectId: 'pushnotifcationdemo-bf646',
    storageBucket: 'pushnotifcationdemo-bf646.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEIV8_L8v_zmeWxRfQ2mxjcTkk6X-xpjM',
    appId: '1:876858730068:ios:930db63cf729f1141cefc1',
    messagingSenderId: '876858730068',
    projectId: 'pushnotifcationdemo-bf646',
    storageBucket: 'pushnotifcationdemo-bf646.appspot.com',
    iosBundleId: 'com.example.pushNotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEIV8_L8v_zmeWxRfQ2mxjcTkk6X-xpjM',
    appId: '1:876858730068:ios:25b5014dfa7d7c061cefc1',
    messagingSenderId: '876858730068',
    projectId: 'pushnotifcationdemo-bf646',
    storageBucket: 'pushnotifcationdemo-bf646.appspot.com',
    iosBundleId: 'com.example.pushNotify.RunnerTests',
  );
}
